development:
  # Configure available database clients. (required)
  clients:
    # Define the default client. (required)
    default:
      # A uri may be defined for a client:
      # uri: 'mongodb://user:password@myhost1.mydomain.com:27017/my_db'
      # Define the name of the default database that Mongoid can connect to.
      # (required).
      database: trade
      hosts:
        - localhost:27017
      options:
        # Change the default write concern. (default = { w: 1 })
        write:
          w: 1
        # Change the default read preference. Valid options for mode are: :secondary,
        # :secondary_preferred, :primary, :primary_preferred, :nearest
        # (default: primary)
        read:
          mode: :secondary_preferred
        # Force the driver to connect in a specific way instead of auto-
        # discovering. Can be one of: :direct, :replica_set, :sharded. Set to :direct
        # when connecting to hidden members of a replica set.
        connect: :direct
        # The maximum number of connections in the connection pool. (default: 5)
        max_pool_size: 10
        # The time to wait, in seconds, in the connection pool for a connection
        # to be checked in before timing out. (default: 1)
        wait_queue_timeout: 1
        # The time to wait to establish a connection before timing out, in seconds.
        # (default: 10)
        connect_timeout: 10

production:
  clients:
    default:
      database: trade
      hosts:
        - threebandb:27017
      options:
        read:
          mode: :secondary_preferred
        connect: :direct
        max_pool_size: 10
        wait_queue_timeout: 1
        connect_timeout: 10 
