_dev_hosts: &DEV_HOSTS
  - mongo

_test_hosts: &TEST_HOSTS
  - mongo

_stg_hosts: &STG_HOSTS


_prd_hosts: &PRD_HOSTS


development:
  sessions:
    default:
      database: trade
      hosts: *DEV_HOSTS
      username: trade
      password: ca$hc0w
  options:
    index: false